# CI de Nível 01 - Disparo manual a partir de 1 clique

name: Execução Manual

on:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalar dependências do Mocha
        run: |
         npm install -D mocha
         npm install -D mochawesome

      - name: Rodar testes com mochawesome
        run: npx mocha trabalho-final.js --reporter mochawesome

      - name: Salvar relatório como artefato
        uses: actions/upload-artifact@v4
        with:
         name: mochawesome-reporter
         path: mochawesome-report/

    